repos:
  # ðŸ”¹ Black (code formatter)
  - repo: https://github.com/psf/black
    rev: '25.1.0'
    hooks:
      - id: black
        args: ["-l", "120"]
        exclude: ^(src/migrations/|services/db_management/migrations/)

  # ðŸ”¹ isort (import sorter, black-compatible)
  - repo: https://github.com/pycqa/isort
    rev: '6.0.1'
    hooks:
      - id: isort
        args: ["--profile", "black"]
        exclude: ^(src/migrations/|services/db_management/migrations/)

  # ðŸ”¹ Flake8 (linting)
  - repo: https://github.com/PyCQA/flake8
    rev: '7.2.0'
    hooks:
      - id: flake8
        args:
          [
            "--ignore=E203,E501,E701,W503,F401,W291,E402,E302,E128,E122",
            "--max-line-length=100",
            "src",
          ]
        exclude: ^(src/migrations/|services/db_management/migrations/)

  # ðŸ”¹ Pre-commit built-in hooks (general hygiene)
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
        exclude: ^(src/migrations/|services/db_management/migrations/)
      - id: end-of-file-fixer
        exclude: ^(src/migrations/|services/db_management/migrations/)
      - id: check-yaml
      - id: check-toml
      - id: check-added-large-files
